In [1]:
!pip install torch

In [2]:
   import torch 
   x = torch.rand(2, 3) 
   print(x)


tensor([[0.8855, 0.2290, 0.6491],
        [0.1858, 0.8622, 0.4151]])


In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
import pandas as pd
import numpy as np
import torch
import sklearn
import matplotlib
import torchinfo, torchmetrics

In [5]:
pip install torch torchvision

Note: you may need to restart the kernel to use updated packages.


In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.2+cpu


In [7]:
scalar = torch.tensor(6)
scalar

tensor(6)

In [8]:
print(1+2)

3


In [9]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim

0

In [11]:
scalar.item()

7

In [12]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

matrix = torch.tensor([7,2])
matrix

In [15]:
matrix = torch.tensor([[7,2],
                       [1,5]])
matrix

tensor([[7, 2],
        [1, 5]])

In [16]:
matrix.ndim

2

In [17]:
matrix.shape

torch.Size([2, 2])

In [18]:
matrix[0]

tensor([7, 2])

In [19]:
matrix[1]

tensor([1, 5])

In [20]:
matrix.shape

torch.Size([2, 2])

In [21]:
TENSOR = torch.tensor([[[1,2,3], 
                        [4,5,6],
                        [7,8,8]]])

In [ ]:
tensor.shape

In [ ]:
tensor[0]

In [ ]:
tensor[0][1][0]

In [ ]:
random_tensor = torch.rand(5,4,5)
random_tensor

In [ ]:
make_zeros = torch.ones(5,4,5)
make_zeros

In [ ]:
random_tensor*make_zeros

In [ ]:
random_tensor.dtype

In [ ]:
one_to_ten = torch.arange(1,11)
one_to_ten

In [ ]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

In [ ]:
#tensor = torch.tensor([[3,2],[3,4]])
tensor1 = torch.tensor([[5,6,8,8],[9,10,11,12]])
#torch.mm(tensor , tensor1)
tensor1.T

In [ ]:
x = torch.tensor([ 10, 10, 21, 1001, 1, 510, 1001, 71, 81, 91])
x

In [ ]:
torch.max(x), x.max()

In [ ]:
torch.min(x), x.min()

In [ ]:
torch.mean(x.type(torch.float64)), x.type(torch.float32).mean()

In [ ]:
torch.sum(x), x.sum()

In [ ]:
x.argmin()

In [ ]:
x[4]

In [ ]:
x.argmax()

In [ ]:
x[1]

In [ ]:
x[0]=100
x

In [ ]:
x_stacked = torch.stack([x,x,x,x])
x_stacked

In [ ]:
squeeze = x.squeeze
squeeze

In [ ]:
torch.tensor([[ 10, 10, 21, 1001, 1, 510, 1001, 71, 81, 91]]).squeeze.shape

In [ ]:
tensor = torch.tensor([[[[1, 0, 2, 3, 4]]]])
tensor.shape
tensor.unsqueeze(dim=0).shape
tensor.shape

In [ ]:
x_original = torch.rand(size=(2,3,4))
x_original

In [ ]:
torch.manual_seed(42)
model_0 = LinearRegressionModel()

In [ ]:
with torch.inference_mode(): 
    y_preds = model_0(x_test)

In [ ]:
plot_predictions(predictions=y_preds)

In [ ]:
loss_fn = nn.L1Loss()
optimizer = torch.optim.SGD(params=model_0.parameters(),
                            lr=0.01)

In [ ]:
print("Rkib")

In [ ]:

import pandas as pd
url = 'https://1drv.ms/x/s!AgwYhUHWP6XVghO7f3vX0h22pmww?e=Qif929.xlsx'
df = pd.read_excel(url)
print(df.head())

In [23]:
import time
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk
import io
import unicodedata
import numpy as np
import re
import string
from numpy import linalg
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.tokenize import PunktSentenceTokenizer
from nltk.tokenize import PunktSentenceTokenizer
from nltk.corpus import webtext
from nltk.stem.porter import PorterStemmer
from nltk.stem.wordnet import WordNetLemmatizer


with open('kindle.txt', encoding ='ISO-8859-2') as f:
	text = f.read()
	
sent_tokenizer = PunktSentenceTokenizer(text)
sents = sent_tokenizer.tokenize(text)

print(word_tokenize(text))
print(sent_tokenize(text))

porter_stemmer = PorterStemmer()

nltk_tokens = nltk.word_tokenize(text)

for w in nltk_tokens:
	print ("Actual: % s Stem: % s" % (w, porter_stemmer.stem(w)))
	

wordnet_lemmatizer = WordNetLemmatizer()
nltk_tokens = nltk.word_tokenize(text)

for w in nltk_tokens:
	print ("Actual: % s Lemma: % s" % (w, wordnet_lemmatizer.lemmatize(w)))
	
text = nltk.word_tokenize(text)
print(nltk.pos_tag(text))

sid = SentimentIntensityAnalyzer() 
tokenizer = nltk.data.load('tokenizers / punkt / english.pickle')

with open('kindle.txt', encoding ='ISO-8859-2') as f:
	for text in f.read().split('\n'):
		print(text)
		scores = sid.polarity_scores(text)
		for key in sorted(scores):
			print('{0}: {1}, '.format(key, scores[key]), end ='')
			
	print()


FileNotFoundError: [Errno 2] No such file or directory: 'kindle.txt'